application: test-thomas
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/dist/index.html
  upload: static/dist/index\.html

- url: /favicon\.ico
  static_files: static/dist/favicon.ico
  upload: static/dist/favicon\.ico

- url: /api/.*
  script: _go_app

- url: /auth/.*
  script: _go_app

- url: /*
  static_dir: static/dist

skip_files:
- ^(static/app/.*)
- ^(static/node_modules/.*)
- ^(node_modules/.*)